### ISSUE TITLE
Discuss evolving `Hackathon::Subscription`

### ISSUE THREAD

**Issue by northeastprince** [hackclub/hackathons-backend#207]
Right now, a [`Hackathon::Subscription`](https://github.com/hackclub/hackathons-backend/blob/e01c19ae3237bbcb3ec7c0804e1fe669fa4f8723/app/models/hackathon/subscription.rb) ties a subscriber to an area they wanna receive hackathon digests for. But it doesn't seem that way when you look at it. Since we want to have notifications for admins and organizers for pertinent submissions and/or their updates, I think a general polymorphic `Subscription` model could be handy.

That leaves the more specific `Hackathon::Subscription` in a bit of a tough spot. I think we should refactor it to something like a `Hackathon::Regional::Subscription`, but it's closely coupled to the complex [`Hackathon::Digest`](https://github.com/hackclub/hackathons-backend/blob/01f549ecb3fad8c34c1f8c781c7bf58f2ac1f07b/app/models/hackathon/digest.rb) system so that might make it even more confusing.

I'd love to get some input on this!

**Comment by garyhtou** [comment]
I don't find the need for a model to handle status update notifications. Could you explain more about what the polymorphic `Subscription` model would do?

Also, I'm in favor of keeping `Hackathon::Subscription` as is because the primary purpose of this application is to notify subscribers based on geographic regions. We don't have a use case for any other type of hackathon subscription, and likely won't in the future.

**Comment by northeastprince** [comment]
I was thinking we could have that model so that admins could have a choice whether to be notified or not, but now that I think about it, we can just have that as a user-level option for admins.
